name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2

      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install VSCE
        run: npm install -g vsce

      - name: Install Dependencies
        run: npm i

      - name: Install VSCE
        run: vsce package
